# Generated by Django 5.0.6 on 2024-07-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='duration_minutes_in_days',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='image',
            field=models.ImageField(default='gym/images/default_image.jpg', upload_to='gym/images'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='intensity',
            field=models.CharField(choices=[('Low ', 'Low'), ('Medium ', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
    ]
