# Generated by Django 5.0.6 on 2024-07-15 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rename_name_fitnessclass_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Gym Fitness Trainer', 'Gym Fitness Trainer'), ('Bodybuilding Trainer', 'Bodybuilding Trainer'), ('Crossfit Trainer', 'Crossfit Trainer'), ('Aerobics Instructor', 'Aerobics Instructor'), ('Yoga Master', 'Yoga Master')], max_length=50)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('height_ft', models.FloatField()),
                ('occupation', models.CharField(max_length=100)),
                ('image', models.ImageField(default='gym/images/instructors/default_istractor.jpg', upload_to='gym/images/instructors/')),
            ],
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.instructor'),
        ),
    ]
