# Generated by Django 5.0.6 on 2024-07-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_fitnessclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='image',
            field=models.ImageField(default='gym/images/classes/default_image.jpg', upload_to='gym/images/classes'),
        ),
    ]
