# Generated by Django 5.0.6 on 2024-07-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_fitnessclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
